### ISSUE TITLE
Remove restify dependency from models

### ISSUE THREAD

**Issue by fmalcher** [hftlclub/node-iltis#42]
Models should be generic, self-contained and not made for a specific environment.
The log models contain a dependency to restify which makes them unusable outside a restify environment.

TODO: Remove restify dependency

**Comment by rweisse** [comment]
The dependency inside the model itself was a copy paste error.

The dependency will stay inside the log-factory and will be used inside the toDbObject function. This is independent from the frontend. It's a backend code part. Otherwise I would have to add two extra lines in each ressouce function.

Nevertheless this could be changed with the revised logging. It wouldn't make any sense to change this now.

**Comment by rweisse** [comment]
But I know what you mean. You have this dependency in your frontend and have to import restify to start it. I will remove it from the factory by introducing the new logging in the next two days.

**Comment by fmalcher** [comment]
The solution for me wa to completely remove those models temporaily
